name: poemas_app
description: Antología poética con índice por autor.
publish_to: 'none'
version: 1.0.7+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^8.0.2
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  share_plus: ^13.1.0
  path_provider: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/poemas.json
  

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/gafas_bigote_splash_mini.png"
  min_sdk_android: 21
  adaptive_icon_background: "#150e0e"
  adaptive_icon_foreground: "assets/icon/gafas_bigote_splash_mini.png"
  android_notification_icon: false
  image_fill_color: "#150e0e"  # fills transparent areas before generating
  remove_alpha_ios: true  

flutter_native_splash:
  color: "#150e0e"
  image: assets/icon/gafas_bigote_splash_mini.png

  android: true
  ios: true

  android_12:
    color: "#150e0e"
    image: assets/icon/gafas_bigote_splash_mini.png
    icon_background_color: "#150e0e"