name: poemas_app
description: Antología poética con índice por autor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.0
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/poemas.json

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icono.png"
  min_sdk_android: 21
  adaptive_icon_background: "#3B2F2F"
  adaptive_icon_foreground: "assets/icon/icono.png"