name: poemas_siglo_de_oro
description: Antología poética con índice por autor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/poemas.json
