#!/usr/bin/env python3
"""
seleccionar.py - build the English app's poemas.json from laurel_convert.py output.

  python3 laurel_convert.py --corpus laurel-corpus --out out      # no --max-lines
  python3 seleccionar.py --poems out/poems.jsonl \
      --asset ../assets/poemas.json --report ranking.md [--top-authors N] [--max-lines N]

Authors are ranked, best known first, and every poem of each selected author
is kept. Ranking:

  1. Tier 1 is laurel_convert.PRIORITY_POETS, the canon the gap report
     already checks. Tier 2 is everyone else.
  2. Within a tier, by English Wikipedia page views of the author's article,
     Sep 2025 - Aug 2026 (autores_vistas.json; articles were matched by search
     and the mismatches corrected by hand). Views measure fame as a person, not
     as a poet - Thoreau and Stevenson outrank Herrick - which is why the tier
     comes first.

Duplicates (same author, same opening line: one poem from two source editions)
are dropped, keeping the first. The app derives Poema.id from author, title and
first line and asserts they are unique, so this is required, not cosmetic.

The report lists every author with running totals of poems, verses and bytes,
so the cut can be chosen by author rank (--top-authors) and/or length.
"""
import argparse
import json
import re
import unicodedata
from pathlib import Path

from laurel_convert import PRIORITY_POETS

AQUI = Path(__file__).resolve().parent


def normalizar(s):
    s = unicodedata.normalize("NFKD", s).lower()
    s = s.replace("’", "'").replace("‘", "'").replace("'", "")
    s = re.sub(r"[^a-z0-9 ]+", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def es_canon(autor):
    return any(p.lower() in autor.lower() for p in PRIORITY_POETS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--poems", required=True)
    ap.add_argument("--asset", required=True)
    ap.add_argument("--report", required=True)
    ap.add_argument("--top-authors", type=int, default=0, help="keep only the N best-ranked authors (0 = all)")
    ap.add_argument("--max-lines", type=int, default=0, help="drop poems longer than this (0 = no cap)")
    args = ap.parse_args()

    vistas = json.loads((AQUI / "autores_vistas.json").read_text(encoding="utf-8"))
    poemas = [json.loads(l) for l in open(args.poems, encoding="utf-8")]

    vistos, unicos, duplicados = set(), [], 0
    for p in poemas:
        clave = (p["author"], normalizar(p["stanzas"][0][0]))
        if clave in vistos:
            duplicados += 1
            continue
        vistos.add(clave)
        unicos.append(p)

    por_autor = {}
    for p in unicos:
        por_autor.setdefault(p["author"], []).append(p)

    def rango(autor):
        v = vistas.get(autor, {}).get("vistas_12m", 0)
        return (0 if es_canon(autor) else 1, -max(v, 0), autor)

    orden = sorted(por_autor, key=rango)
    if args.top_authors:
        orden = orden[: args.top_authors]

    salida, filas = [], []
    total_p = total_v = total_b = 0
    for i, autor in enumerate(orden, 1):
        ps = [p for p in por_autor[autor] if not args.max_lines or p["line_count"] <= args.max_lines]
        entradas = [{"titulo": p["title"], "autor": autor, "texto": p["text"]} for p in ps]
        salida += entradas
        b = sum(len(json.dumps(e, ensure_ascii=False).encode()) for e in entradas)
        v = sum(p["line_count"] for p in ps)
        total_p += len(ps); total_v += v; total_b += b
        filas.append("| %d | %s | %s | %s | %d | %d | %d | %.2f |" % (
            i, autor, "1" if es_canon(autor) else "2",
            format(vistas.get(autor, {}).get("vistas_12m", 0), ","),
            len(ps), sum(1 for p in ps if p["line_count"] > 60), total_p, total_b / 1e6))

    Path(args.asset).write_text(json.dumps(salida, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    informe = [
        "# English anthology: author ranking", "",
        "Generated by `seleccionar.py`. Tier 1 = the canon in `PRIORITY_POETS`; within a tier, "
        "Wikipedia page views (Sep 2025 - Aug 2026). Every poem of each author, "
        + ("capped at %d verses." % args.max_lines if args.max_lines else "no length cap.") ,
        "",
        "**%d poems, %d authors, %s verses, %.2f MB** (%d duplicates dropped)." % (
            total_p, len(orden), format(total_v, ","), total_b / 1e6, duplicados),
        "",
        "| # | Author | Tier | Views | Poems | Over 60 verses | Running poems | Running MB |",
        "|---:|---|:-:|---:|---:|---:|---:|---:|",
    ] + filas + [""]
    Path(args.report).write_text("\n".join(informe), encoding="utf-8")
    print("%d poems, %d authors, %.2f MB, %d duplicates dropped" % (total_p, len(orden), total_b / 1e6, duplicados))


if __name__ == "__main__":
    main()
